# Prepare the input files for the Debian (deb) and Redhat (rpm) packages for CVMFS clients.
---
- name: Prepare Deb and RPM packages
  hosts: localhost
  vars:
    package_vendor: EESSI
    package_maintainer: EESSI <eessi@list.rug.nl>
    package_description: CVMFS configuration package for EESSI.
    package_source_dir: "{{ lookup('env', 'GITHUB_WORKSPACE') | default('/tmp', True) }}/package"
  tasks:
    - name: Create directory structure for the CVMFS config
      file:
       path: "{{ item }}"
       state: directory
       mode: 0775
      with_items:
      - "{{ package_source_dir }}"
      - "{{ package_source_dir }}/etc"
      - "{{ package_source_dir }}/etc/cvmfs"
      - "{{ package_source_dir }}/etc/cvmfs/keys"
      - "{{ package_source_dir }}/etc/cvmfs/keys/{{ eessi_cvmfs_server_urls.domain }}"
      - "{{ package_source_dir }}/etc/cvmfs/default.d"
      - "{{ package_source_dir }}/etc/cvmfs/domain.d"

    - name: Make EESSI CVMFS public key file
      copy:
        content: "{{ eessi_cvmfs_config_repo.key.key }}"
        dest: "{{ package_source_dir }}{{ eessi_cvmfs_config_repo.key.path }}"
        mode: 0644

    - name: Make EESSI CVMFS domain configuration file
      copy:
        content: |
          CVMFS_SERVER_URL="{{ eessi_cvmfs_config_repo.urls|join(';') }}"
          CVMFS_KEYS_DIR="{{ eessi_cvmfs_repositories.key_dir }}"
          CVMFS_USE_GEOAPI="yes"
        dest: "{{ package_source_dir }}/etc/cvmfs/domain.d/{{ eessi_cvmfs_server_urls.domain }}.conf"
        mode: 0644

#    - name: Make EESSI CVMFS default configuration file
#      copy:
#        content: |
#          CVMFS_CONFIG_REPOSITORY="{{ eessi_cvmfs_config_repo.repository.repository }}"
#          CVMFS_DEFAULT_DOMAIN="{{ eessi_cvmfs_config_repo.domain }}"
#        dest: "{{ package_source_dir }}/etc/cvmfs/default.d/80-eessi-cvmfs.conf"
#        mode: 0644
