---

# ansible-galaxy role install -r requirements.yml -p ./roles
roles:

  - name: galaxyproject.cvmfs
    src: https://github.com/galaxyproject/ansible-cvmfs
    version: 7fa3a81

  - name: geerlingguy.repo-epel
    version: 3.0.0
