# Install CVMFS Stratum 1 server(s).
---
- name: CVMFS Stratum 1
  hosts: cvmfsstratum1servers
  pre_tasks:
    - name: Fix that adds squid as a dependency for Debian systems
      set_fact:
        cvmfs_packages:
          stratum1:
            - apache2
            - cvmfs-server
            - cvmfs-config-default
            - squid
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_facts['os_family'] == 'RedHat'
    - galaxyproject.cvmfs
