# Install CVMFS Stratum 1 server(s).
---
- name: CVMFS Stratum 1
  hosts: cvmfsstratum1servers
  vars:
    #cvmfs_srv_device: /dev/sdb
    cvmfs_repositories: "{{ eessi_cvmfs_repositories + [eessi_cvmfs_config_repo.repository] }}"
    cvmfs_squid_conf_src: eessi_stratum1_squid.conf.j2
  roles:
    - geerlingguy.repo-epel
    - cvmfs
