- name: CVMFS
  hosts: cvmfsstratum1servers
  vars:
    #cvmfs_srv_device: /dev/sdb
    cvmfs_repositories: "{{ eessi_cvmfs_repositories + [eessi_cvmfs_config_repo.repository] }}"
  roles:
    - geerlingguy.repo-epel
    - cvmfs
