- name: CVMFS
  hosts: cvmfsstratum0servers
  vars:
    cvmfs_numfiles: 4096
    cvmfs_server_urls:
      - domain: eessi-hpc.org
        urls:
          - "http://cvmfs-s0.eessi-hpc.org/cvmfs/@fqrn@"
    cvmfs_repositories: "{{ eessi_cvmfs_repositories }}"
  roles:
    - galaxyproject.cvmfs
