# Start a transaction on the Stratum 0 and put all the files for the config repo in place.
# Note: first deploy your Stratum 0 and make sure that group_vars/all.yml contains the right configuration,
#       including all the keys of the repositories that have to be configured.
---
- name: CVMFS
  hosts: cvmfsstratum0servers
  tasks:
    - name: Start the CVMFS transaction, create directories, and copy files
      block:
        - name: start CVMFS transaction
          shell: cvmfs_server transaction "{{ eessi_cvmfs_config_repo.repository.repository }}"

        - name: create directories
          file:
            path: "{{ item }}"
            state: directory
          with_list:
            - "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/keys/{{ eessi_cvmfs_config_repo.domain }}"
            - "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/contact"
            - "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/domain.d"

        - name: deploy public keys
          copy: content="{{ item.key }}" dest="/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}{{ item.path }}"
          with_items: "{{ eessi_cvmfs_keys }}"

        - name: create contacts file
          copy:
            content: "{{ eessi_email }}\n"
            dest: "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/contact/{{ eessi_cvmfs_config_repo.domain }}"

        - name: create domain configuration file
          copy:
            content: |
              CVMFS_SERVER_URL="{{ eessi_cvmfs_config_repo.urls | join(';') }}"
              CVMFS_KEYS_DIR="/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/keys/{{ eessi_cvmfs_config_repo.domain }}"
              CVMFS_USE_GEOAPI="{{ eessi_cvmfs_server_urls[0].use_geoapi | default(false) | ternary('yes', 'no') }}"
            dest: "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/domain.d/{{ eessi_cvmfs_config_repo.domain }}.conf"

        - name: create default CVMFS configuration file
          copy:
            content: |
              # For reference see https://sft.its.cern.ch/jira/browse/CVM-878
              CVMFS_LOW_SPEED_LIMIT=10000
            dest: "/cvmfs/{{ eessi_cvmfs_config_repo.repository.repository }}/etc/cvmfs/default.conf"

        - name: publish CVMFS transaction
          shell: cvmfs_server publish "{{ eessi_cvmfs_config_repo.repository.repository }}"
      rescue:
        - name: cancel the transaction
          shell: cvmfs_server abort -f "{{ eessi_cvmfs_config_repo.repository.repository }}"
