# Install a CVMFS Stratum 0 server.
---
- name: CVMFS Stratum 0
  hosts: cvmfsstratum0servers
  vars:
    cvmfs_repositories: "{{ eessi_cvmfs_repositories + [eessi_cvmfs_config_repo.repository] }}"
  roles:
    - geerlingguy.repo-epel
    - cvmfs
