# Install a CVMFS Stratum 0 server.
---
- name: CVMFS Stratum 0
  hosts: cvmfsstratum0servers
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_facts['os_family'] == 'RedHat'
    - galaxyproject.cvmfs
