---
- name: Create a meta.json containing the CVMFS Server Meta Information
  ansible.builtin.copy:
    content: "{{ cvmfs_metadata | to_nice_json(indent=2, sort_keys=false) }}"
    dest: "/srv/cvmfs/info/v1/meta.json"
    owner: root
    group: root
    mode: 0644
  become: true
...
