# Specifications of files and symlinks for the pilot.eessi-hpc.org CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
files:
  - name: .cvmfsdirtab
    dest: ''
    mode: '644'

symlinks:
  latest: 2021.06
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
  versions/2021.06: ../2021.06
