files:
  .cvmfsdirtab: |
    # Compatibility layer paths:
    # /<version>/compat/{linux,macos}/{aarch64,ppc64le,x86_64}
    /*/compat/*/*
    /*/compat/*/*/var
    /*/compat/*/*/var/db/repos

    # Software layer paths:
    # /<version>/software/{linux,macos}/{aarch64,ppc64le,x86_64}/<vendor>/<microarchitecture>/software
    /*/software/*/*/*/*/software
    /*/software/*/*/*/*/software/*/*
    /*/software/*/*/*/*/modules
    # generic and graviton2 are one level less deep
    /*/software/*/*/*/software
    /*/software/*/*/*/software/*/*
    /*/software/*/*/*/modules

symlinks:
  latest: 2021.06
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
