---
# vars file for eessi project

# Automatically configure EESSI CVMFS repos.
eessi_cvmfs_repos_enabled: true

# Email address for the project.
eessi_email: eessi@list.rug.nl

#
# Defaults for eessi.io repos.
#

# We do not use a config repo anymore.
eessi_cvmfs_config_repo: {}

# Public keys for the repositories, which you can find on the Stratum 0 at:
# /etc/cvmfs/keys/*.pub
# Note: you first have to run the stratum0.yml playbook once to generate the repositories and keys.
eessi_cvmfs_keys:
  - path: /etc/cvmfs/keys/eessi.io/software.eessi.io.pub
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx/MGKNYeXgAzNGRmyy6c
      AHPzXOfA+MPEdDsYNxz4FWCq24HqwDGCdrGFWuAPPnocumMpVqU6G4nhjYNEf7HY
      VBXub9sAS7cl7jycN+n82A7hgoZqkTlRpBTCv30zAII7MsCfSakxXx5PLIWFe10i
      8Cs7heb2ZAdDXPCJE1CQMnhknAu1ucKfZz5mB6DP6pGiH30rGyFiEH7M5HsfiA9T
      VkfWMPmd10YmboA9GsNhng8SWoWX8rMDIupAmtYTxiS3bdslrAa7hThpymtx6Jcb
      ZhEaIPp0ACctyk4+B6ZXnZX0HHtqqpyP6mo2QMMc6fQI9RlvO9hboqoESza5FzJ5
      FQIDAQAB
      -----END PUBLIC KEY-----

# URLs for all the Stratum 1 servers.
eessi_cvmfs_server_urls:
  - domain: eessi.io
    use_geoapi: true
    urls:
      - "http://aws-eu-central-s1.eessi.science/cvmfs/@fqrn@"
      - "http://azure-us-east-s1.eessi.science/cvmfs/@fqrn@"

# Configuration of all the repositories.
eessi_cvmfs_repositories:
  - repository: software.eessi.io
    stratum0: rug-nl-s0.eessi.science
    owner: "{{ cvmfs_repo_owner | default('root') }}"
    key_dir: /etc/cvmfs/keys/eessi.io
    server_options:
      - CVMFS_AUTO_GC=false
      - CVMFS_AUTO_TAG_TIMESPAN="30 days ago"
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []
    use_for_ci: false

# Override all the Galaxy defaults by our EESSI defaults.
# This is required, beucase the galaxy_* variables are used inside the Ansible tasks.
galaxy_cvmfs_config_repo: "{{ eessi_cvmfs_config_repo }}"
galaxy_cvmfs_keys: "{{ eessi_cvmfs_keys }}"
galaxy_cvmfs_server_urls: "{{ eessi_cvmfs_server_urls }}"
galaxy_cvmfs_repositories: "{{ eessi_cvmfs_repositories }}"
galaxy_cvmfs_repos_enabled: "{{ eessi_cvmfs_repos_enabled }}"
