name: Build and publish EESSI client Docker image
on:
  push:
    branches:
      - main
    paths:
      - containers/Dockerfile.EESSI-client*
      - containers/build-or-download-cvmfs-rpm.sh
      - .github/workflows/build-publish-containers.yml

  # also rebuild the containers for new releases of filesystem-layer:
  # this often means that we have a new CVMFS configuration package
  release:
    types: [published]
 
jobs:
  build_and_publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64, ppc64le]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/EESSI/client-pilot:centos7
          file: containers/Dockerfile.EESSI-client-pilot-centos7
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: true
