name: Build and publish EESSI container images
on:
  push:
    branches:
      - main
    paths:
      - containers/Dockerfile.EESSI-*
      - containers/build-or-download-cvmfs-*.sh

  pull_request:
    branches:
      - main
    paths:
      - containers/Dockerfile.EESSI-client*
      - containers/build-or-download-cvmfs-rpm.sh

  # also rebuild the containers for new releases of filesystem-layer:
  # this often means that we have a new CVMFS configuration package
  release:
    types: [published]
 
jobs:
  build_and_publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        tag: ['client-pilot:centos7', 'fuse-overlay:debian10']

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert and store repository owner in lowercase, replace colon in tag names by hyphen
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          tag=${{ matrix.tag }}
          echo DOCKERFILE=Dockerfile.EESSI-${tag//:/-} >> $GITHUB_ENV

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }}
          file: containers/${{ env.DOCKERFILE }}
          platforms: linux/amd64, linux/arm64, linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
