name: Build packages

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_deb:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with debian:stretch
      uses: roles-ansible/check-ansible-debian-stretch-action@master
      with:
        targets: "./build-packages.yml"
        hosts: "localhost"

    - name: upload package as artifact
      uses: actions/upload-artifact@v2
      with:
        #name: deb_package
        path: ${{ github.workspace }}/build/*.deb
