name: Build packages

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with debian:stable
      uses: roles-ansible/check-ansible-debian-stable-action@master
      with:
        targets: "./build-packages.yml"
        hosts: "localhost"
        requirements: "freedomofpress.build-debian-package"
