name: Build packages

on: [push, pull_request]

jobs:
  debian:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        source_directory: templates # lolcat # optional, relative to workspace directory
        artifacts_directory: output # optional, relative to workspace directory
