name: Test containers

on: [push, pull_request]

jobs:
  test-client-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file containers/Dockerfile.EESSI-client-pilot-centos7
