name: Test Ansible Playbooks

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master

jobs:

  stratum0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Stratum 0 playbook
        uses: ./.github/actions/test-filesystem-layer-playbooks
        with:
          playbook: "stratum0.yml"
